### ISSUE TITLE
Numbers don't add up in cart

### ISSUE THREAD

**Issue by zizhouW** [nayakashu/coffee-shop-pos#1]
you probably forgot to include the base price of the item

**Comment by nayakashu** [comment]
@zizhouW Just saw this one. Will check this. Thank you for raising this. 👍🏼

**Comment by nayakashu** [comment]
@zizhouW 

Have added the base price in the cart item now.

![image](https://user-images.githubusercontent.com/20873985/95321474-b6deee00-08b8-11eb-983b-00fdb96b1c62.png)

If this looks good then you can close this issue.

Thanks again for your feedback.
